if has("gui_running")
  set guifont=Fira\ Code\ Retina:h24
  set anti " Anti-aliased fonts
  set transparency=0
  set columns=100
  set lines=30
else
  set guifont=Fira\ Code\ Retina:h24
  set anti " Anti-aliased fonts
end
